services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: r007_U53r_PA55w0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    image: raynersim/backend:v1.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=r007_U53r_PA55w0rd
      - GEMINI_API_KEY=AIzaSyCDond6yeve5adwKkZtPEBEZFOk0sboJjQ
      - FRONTEND_EC2_HOST=100.113.192.51
      - JWT_SECRET_KEY=b9bfa3684e916e348213eaba6a240cc93e7b1d2175a35c19ee7afe50b3d4c7ad
      - JWT_EXP_TIME=3600000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=100.113.192.51
        - NEXT_PUBLIC_BACKEND_EC2_HOST=100.113.192.51
    image: raynersim/frontend:v1.0
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=100.113.192.51
      - NEXT_PUBLIC_BACKEND_EC2_HOST=100.113.192.51
    depends_on:
      - backend

volumes:
  postgres_data: